/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graph.wedding.planner;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.*;

/**
 *
 * @author Dell
 */
public class RelationsForm extends javax.swing.JFrame {
    
    public String Comboselected;
    public int[] Listselected;
    public String[] guestsNames;
    public int numOfTables = 0;
    public Graph<String> g = new Graph<String>();

    /**
     * Creates new form RelationsForm
     */
    public RelationsForm() {
        initComponents();
        
        this.guestList.setModel(new DefaultListModel());
        DefaultListModel model = (DefaultListModel)this.guestList.getModel();
        
        this.guestComboBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                getFormGuests(guestsNames);
            }
        });
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        guestComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        guestList = new javax.swing.JList<>();
        getTablesButton = new javax.swing.JButton();
        setRelationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wedding Planner");
        getContentPane().setLayout(null);

        jLabel1.setText("Select guests who know each other:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 210, 30);

        guestComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(guestComboBox);
        guestComboBox.setBounds(20, 80, 150, 30);

        guestList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(guestList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(210, 80, 340, 260);

        getTablesButton.setText("Get Tables");
        getTablesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTablesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(getTablesButton);
        getTablesButton.setBounds(210, 390, 340, 30);

        setRelationButton.setText("Set Relation");
        setRelationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRelationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(setRelationButton);
        setRelationButton.setBounds(210, 350, 340, 30);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("(You can select multiple guests from the right list)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 20, 320, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void getFormGuests(String[] Guests) {
        
        int counter = 0;
        
        this.guestList.setModel(new DefaultListModel());
        DefaultListModel model = (DefaultListModel)this.guestList.getModel();
        for(String v : Guests) {
            if(v != this.guestComboBox.getSelectedItem()) {
                model.addElement(v);
                counter++;
            }
        }
        this.guestsNames = Guests;
    }
    
    
    private void getTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTablesButtonActionPerformed
        
        JOptionPane.showMessageDialog(null, "Number of Tables: " + g.numOfTables(), "Number of Tables", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_getTablesButtonActionPerformed

    private void setRelationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRelationButtonActionPerformed
        
        Comboselected = this.guestComboBox.getSelectedItem().toString();
        Listselected = this.guestList.getSelectedIndices();
        
        //int temp = 0;
        
        for(int i = 0; i < Listselected.length; i++) {
            g.addEdge(Comboselected, this.guestList.getModel().getElementAt(Listselected[i]));
        }
        
    }//GEN-LAST:event_setRelationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelationsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getTablesButton;
    public javax.swing.JComboBox<String> guestComboBox;
    public javax.swing.JList<String> guestList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton setRelationButton;
    // End of variables declaration//GEN-END:variables
}
